envoy:
  enabled: false

k8sServiceHost: "k8master.service.consul"
k8sServicePort: "6443"

serviceAccounts:
  cilium:
    create: true
  nodeinit:
    create: true
  envoy:
    create: false
  etcd:
    create: false
  operator:
    create: true
  preflight:
    create: true
  relay:
    create: true
  ui:
    create: true
  clustermeshApiserver:
    create: true
  clustermeshcertgen:
    create: true
  hubblecertgen:
    create: false

ipam:
  operator:
    # -- IPv4 CIDR list range to delegate to individual nodes for IPAM.
    clusterPoolIPv4PodCIDRList: ["10.244.0.0/16"]
    # -- IPv4 CIDR mask size to delegate to individual nodes for IPAM.
    clusterPoolIPv4MaskSize: 22

operator:
  prometheus:
    enabled: true
    metricsService: true
    serviceMonitor:
      enabled: true

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

hubble:
  enabled: true
  metrics:
    enabled:
      - flow
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - icmp
      - http
    serviceMonitor:
      enabled: true

  relay:
    enabled: true
    prometheus:
      enabled: true
    serviceMonitor:
      enabled: true
  ui:
    backend:
    frontend:
      server:
        ipv6:
          enabled: false
    enabled: true

# Valid options are "true", "false", "disabled" (deprecated), "partial" (deprecated), "strict" (deprecated).
# ref: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/
kubeProxyReplacement: "true"

nodeinit:
  enabled: true

authentication:
  enabled: true