User:
  name: Vijay

replicaCount: 2

image:
  repository: nginx:latest

labels:
  app: web-app
  type: frontend

serviceAccount:
  enabled: true
  name: demo-sa

service:
  annotations:
    envlabel: $(#environment["optouttest"].dummyoutput)$
  protocol: TCP
  type: ClusterIP 
  port: 80
  labels:
    name: webapp-service

deployment:
  port: 80

http_proxy: ""
https_proxy: ""
no_proxy: ""
