apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: outputtestenvironment
  project: defaultproject
spec:
  template:
    name: outputtestenvtemp
    version: v1
    versionState: unspecified
