apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: s3-custom-environment
  project: defaultproject
spec:
  template:
    name: s3-custom-et
    version: v1
    versionState: unspecified
  variables:
  - name: bucket
    options:
      override:
        type: allowed
    value: vijaysenvtestbucket05132025
    valueType: text
