apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: ingress-nginx-controller
  project: defaultproject
spec:
  artifact:
    artifact: {}
    type: Helm
  namespace: ingress-nginx
  sharing: {}
